# Generated by Django 5.2.6 on 2025-09-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="synclog",
            old_name="added_count",
            new_name="created_count",
        ),
    ]
