# Generated by Django 5.2.6 on 2025-09-22 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_alter_event_options_event_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutboxMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic", models.CharField(max_length=255)),
                ("payload", models.JSONField()),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                db_index=True, verbose_name="Дата проведения мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                db_index=True, max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="venue",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="events.venue",
                verbose_name="Площадка",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fullname", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("confirmation_code", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация на мероприятие",
                "verbose_name_plural": "Регистрации на мероприятия",
                "unique_together": {("event", "email")},
            },
        ),
    ]
