# Generated by Django 5.2.6 on 2025-09-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_outboxmessage_alter_event_date_alter_event_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="eventregistration",
            old_name="fullname",
            new_name="full_name",
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="outboxmessage",
            name="id",
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
