# Generated by Django 5.2.6 on 2025-09-23 08:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0006_rename_fullname_eventregistration_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["-event_time"],
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.RenameField(
            model_name="event",
            old_name="date",
            new_name="event_time",
        ),
        migrations.AddField(
            model_name="event",
            name="registration_deadline",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
